"""Add creator onboarding progress tracking to users

Revision ID: stu123vwx456
Revises: nop789qrs012
Create Date: 2025-07-22 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'stu123vwx456'
down_revision = 'nop789qrs012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_step', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('onboarding_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_data')
    op.drop_column('users', 'onboarding_step')
    # ### end Alembic commands ###